#!/bin/zsh

CLI_NAME="Desktop-Cleanup"
CLI_PATH="/usr/local/bin/$CLI_NAME"

LAUNCH_AGENT_NAME="com.khronokernel.desktop-cleanup"
LAUNCH_AGENT_PATH="/Library/LaunchAgents/$LAUNCH_AGENT_NAME.plist"

CURRENT_USER=$(stat -f "%Su" /dev/console)

if [[ -f "$LAUNCH_AGENT_PATH" ]]; then
    echo "Unloading $LAUNCH_AGENT_NAME LaunchAgent..."
    launchctl bootout gui/"$(id -u "$CURRENT_USER")"/"$LAUNCH_AGENT_NAME"
fi

if [[ -f "$CLI_PATH" ]]; then
    echo "Removing $CLI_NAME CLI..."
    rm -f "$CLI_PATH"
fi

if [[ -f "$LAUNCH_AGENT_PATH" ]]; then
    echo "Removing $LAUNCH_AGENT_NAME LaunchAgent..."
    rm -f "$LAUNCH_AGENT_PATH"
fi